LEXICON_BANK_CARD = {
    "start_question": "Какая у вас проблема с банковской картой?",
    "stop_list": "Стоп-лист",
    "region_card": "Карта регионов",
    "back": "Назад",
    "input_card_prompt": "Введите номер карты, чтобы создать обращение",
    "info_text": "Вывод справочной информации по карте регионов",
    "info_url_text": "Справочная информация",
    "info_url": "https://www.google.ru/",
}

LEXICON_TRANSPORT_CARD = {
    "start_question": "У Вас есть транспортная карта?",
    "yes": "Да",
    "no": "Нет",
    "back": "Назад",
    "get_transport_card_options": "Получить транспортную карту можно несколькими способами:",
    "download_app": "Скачать приложение",
    "download_app_instruction": "Инструкция по скачиванию приложения",
    "download_app_info_url": "https://www.google.ru",
    "get_corporate_card": "Получить корпоративную карту",
    "get_corporate_card_instruction": "Инструкция по получению корпоративной карты",
    "get_corporate_card_info_url": "https://www.google.ru",
    "get_another_card": "Получить другую карту",
    "get_another_card_instruction": "Инструкция по получению другой карты",
    "get_another_card_info_url": "https://www.google.ru",
    "get_otk": "Получить ОТК",
    "get_otk_instruction": "Инструкция по получению ОТК",
    "get_otk_info_url": "https://www.google.ru",
    "info_url_text": "Справочная информация",
    "info_url": "https://www.google.ru",
    "choose_option": "Выберите подходящий вариант:",
    "input_card_number": "Ввести номер карты",
    "dont_know_card_number": "Не знаю номер карты",
    "unknown_card_number_prompt": "Не знаю номер карты\nВыберите подходящую льготу",
    "schoolboy": "Школьник",
    "student": "Студент",
    "pensioner": "Пенсионер",
    "beneficiary": "Льготник",
    "enter_card_number": "Введите номер карты:",
}

LEXICON_FAQ_DIALOG = {
    "faq_list": "Список часто задаваемых вопросов",
    "question_1": "Вопрос 1",
    "question_2": "Вопрос 2",
    "question_3": "Вопрос 3",
    "back": "Назад",
}